
### POST
http://localhost:8080/auth/login
Content-Type: application/json

{
    "login":"admin",
    "password":"test123"
}

### POST
http://localhost:8080/auth/register
Content-Type: application/json

{
    "login":"felipevieiramota",
    "password":"felipe_adm",
    "role":"USER"
}