server:
  port: 11000

spring:

  application:
    name: agendamentos

  # Database Configuration
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/agendamentos-db
  #   username: postgres
  #   password: postgres
  #   driver-class-name: org.postgresql.Driver
  # jpa:
  #   hibernate:
  #     ddl-auto: create
  #   show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:authentication;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: ${JWT_SECRET:this_is_my_super_secure_secret_key_123!}

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE

#springdoc:
#  swagger-ui:
#    path: /springdoc/swagger-ui.html
#    enabled: true
#    disable-swagger-default-url: true
#    url: /springdoc/api-docs
#  api-docs:
#    path: /springdoc/api-docs

springdoc:
  swagger-ui:
    path: /agendamentos/swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    url: /agendamentos/api-docs
  api-docs:
    path: /agendamentos/api-docs