server:
  port: 10000

spring:
  application:
    name: agendamentos

  # Configuração do datasource para PostgreSQL
  datasource:
    url: jdbc:postgresql://testejp:5434/tech5  # Alterado para PostgreSQL
    driverClassName: org.postgresql.Driver     # Driver do PostgreSQL
    username: postgres                         # Seu nome de usuário do PostgreSQL
    password: fiap5                            # Sua senha no PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update
api:
  security:
    token:
      secret: ${JWT_SECRET:this_is_my_super_secure_secret_key_123!}

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE

springdoc:
  swagger-ui:
    path: /agendamentos/swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    url: /agendamentos/api-docs
  api-docs:
    path: /agendamentos/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
