server:
  port: 9000

spring:

  application:
    name: consultas

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/consultas-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
