server:
  port: 12000

spring:

  application:
    name: especialidades

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:authentication;
    driverClassName: org.h2.Driver
    username: sa
    password:

api:
  security:
    token:
      secret: ${JWT_SECRET:this_is_my_super_secure_secret_key_123!}

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE

springdoc:
  swagger-ui:
    path: /especialidades/swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    url: /especialidades/api-docs
  api-docs:
    path: /especialidades/api-docs