
server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:

        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/auth/**

        - id: auth-swagger
          uri: http://localhost:9000
          predicates:
            - Path=/api/**, /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html, /springdoc/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST

logging:
  level:
    org.springframework.cloud.gateway: TRACE