server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # Colocar as rotas

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true
    enabled: true
    urls:
      -# Colocar os serviços


