
server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:

        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/auth/**

        - id: auth-swagger
          uri: http://localhost:9000
          predicates:
            - Path=/api/**, /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html, /springdoc/**

        - id: agendamentos
          uri: http://localhost:11000
          predicates:
            - Path=/agendamentos/**

        - id: agendamentos-swagger
          uri: http://localhost:11000
          predicates:
            - Path=/api/**, /v3/api-docs/**, /swagger-ui/**, /agendamentos/swagger-ui.html, /agendamentos/springdoc/**

        - id: consultas
          uri: http://localhost:12000
          predicates:
            - Path=/consultas/**

        - id: consultas-swagger
          uri: http://localhost:12000
          predicates:
            - Path=/api/**, /v3/api-docs/**, /swagger-ui/**, /consultas/swagger-ui.html, /consultas/springdoc/**

        - id: exames
          uri: http://localhost:13000
          predicates:
            - Path=/exames/**

        - id: exames-swagger
          uri: http://localhost:13000
          predicates:
            - Path=/api/**, /v3/api-docs/**, /swagger-ui/**, /exames/swagger-ui.html, /exames/springdoc/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST

logging:
  level:
    org.springframework.cloud.gateway: TRACE