server:
  port: 8080

spring:
  boot:
    admin:
      client:
        url: http://localhost:20000
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: autorizacao-usuarios
          uri: http://localhost:9000
          predicates:
            - Path=/autorizacao-usuarios/**

        - id: autorizacao-usuarios-swagger
          uri: http://localhost:9000
          predicates:
            - Path=/api/**, /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html, /autorizacao-usuarios/**

        - id: agendamentos
          uri: http://localhost:10000
          predicates:
            - Path=/agendamentos/**

        - id: agendamentos-swagger
          uri: http://localhost:10000
          predicates:
            - Path=/api/**, /v3/api-docs/**, /swagger-ui/**, /agendamentos/**

        - id: especialidades
          uri: http://localhost:11000
          predicates:
            - Path=/especialidades/**

        - id: especialidades-swagger
          uri: http://localhost:11000
          predicates:
            - Path=/api/**, /v3/api-docs/**, /swagger-ui/**, /especialidades/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST

logging:
  level:
    org.springframework.cloud.gateway: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"