server:
  port: 9002

spring:

  application:
    name: API de Notificacoes (notificacao-service)

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/notificacao-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
