server:
  port: 11000

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      default-binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        enviar-out-0:
          destination: notificacao.exchange
          content-type: application/json
          producer:
            exchange-type: fanout
        receber-in-0:
          destination: notificacao.exchange
          consumer:
            exchange-type: fanout

twilio:
  conta_sid: AC1173eb313a4cab7140cb6140ed2b0ecf
  auth_token: 876740ff405eb8219a27bf3b4782834d
  numero: +19497827123


logging:
  level:
    org.springframework.cloud.stream: DEBUG
    org.springframework.amqp.rabbit: DEBUG
    org.springframework.messaging: DEBUG