server:
  port: 9000

spring:
  boot:
    admin:
      client:
        instances:
          name: autorizacaoeusuarios
        url: http://localhost:20000
  application:
    name: autorizacao-usuarios
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:authentication;
    driverClassName: org.h2.Driver
    username: postech
    password: fase5
api:
  security:
    token:
      secret: ${JWT_SECRET:this_is_my_super_secure_secret_key_123!}

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    root: INFO
    br.com.agendafacilsus: DEBUG

  file:
    name: logs/app.log
springdoc:
  swagger-ui:
    path: /autorizacao-usuarios/swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    url: /autorizacao-usuarios/api-docs
  api-docs:
    path: /autorizacao-usuarios/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
