spring:
  boot:
    admin:
      client:
        instances:
          name: autorizacaoeusuarios
        url: http://localhost:20000
  application:
    name: autorizacaoeusuarios
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:authentication;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 9000

api:
  security:
    token:
      secret: ${JWT_SECRET:this_is_my_super_secure_secret_key_123!}

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE

springdoc:
  swagger-ui:
    path: /springdoc/swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    url: /springdoc/api-docs
  api-docs:
    path: /springdoc/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"